### ISSUE TITLE
Parameters -> Pigments

### ISSUE THREAD

**Issue by fcarvalhopacheco** [cchdo/exchange#26]
Just wondering if you can also use `mass_concentration_of_phaeopigments_in_sea_water`. Someone else submitted this one!

Cheers
Fernando

**Comment by DocOtak** [comment]
I looked at using it the other day, and our database makes a distinction between pheophytin and pheophorbide and I interpreted this name as being the combination of all these things.

We (CCHDO) also don't usually have this parameter in our actual data, they tends to go to NASA SeaBASS.
