### ISSUE TITLE
Change request policy needed

### ISSUE THREAD

**Issue by DocOtak** [cchdo/exchange#4]
An explicit "how to suggest changes" policy is needed, it should include a timeline as well. Some suggestions:
- All suggestions must come in the form of a pull request or open issue on github.
- Issues should be explicitly tagged as "Accepted" for inclusion when they will be.
- Issues should be explicitly tagged as "Rejected" with a reason when the issue is closed.
- When an Issue is to be "Accepted" a it should be added to a release milestone.
- Accepted issues should have a 2 month comment period where objections to inclusion may be raised.

**Comment by asdossant** [comment]
We decided not to do this. Changes will be made if necessary. Ad hoc, no official policy.
